# Generated by Django 5.2 on 2025-07-13 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='projeto',
        ),
        migrations.RemoveField(
            model_name='progressoaluno',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='progressoaluno',
            name='projeto',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='alunos',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='clientes',
        ),
        migrations.RemoveField(
            model_name='reuniao',
            name='projeto',
        ),
        migrations.RemoveField(
            model_name='projetotecnologia',
            name='projeto',
        ),
        migrations.RemoveField(
            model_name='projetotecnologia',
            name='tecnologia',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('restaurante', 'Restaurante'), ('instituicao', 'Instituição')], max_length=14),
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField()),
                ('comentario', models.TextField(blank=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('avaliado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_recebidas', to='app.usuario')),
                ('avaliador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_feitas', to='app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('coletado', 'Coletado')], default='disponivel', max_length=20)),
                ('restaurante', models.ForeignKey(limit_choices_to={'tipo_usuario': 'restaurante'}, on_delete=django.db.models.deletion.CASCADE, related_name='doacoes', to='app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_recebidas', to='app.usuario')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_enviadas', to='app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20)),
                ('doacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.doacao')),
                ('instituicao', models.ForeignKey(limit_choices_to={'tipo_usuario': 'instituicao'}, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='app.usuario')),
            ],
        ),
        migrations.DeleteModel(
            name='Entrega',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='ProgressoAluno',
        ),
        migrations.DeleteModel(
            name='Reuniao',
        ),
        migrations.DeleteModel(
            name='Projeto',
        ),
        migrations.DeleteModel(
            name='ProjetoTecnologia',
        ),
        migrations.DeleteModel(
            name='Tecnologia',
        ),
    ]
