# Generated by Django 5.2 on 2025-07-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_feedback_cliente_remove_feedback_projeto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doacao',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='doacoes/'),
        ),
    ]
