# Generated by Django 5.2 on 2025-07-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_doacao_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('item', models.CharField(max_length=100)),
                ('qtd', models.CharField(max_length=50)),
                ('imagem', models.URLField()),
            ],
        ),
    ]
