# Generated by Django 5.2.4 on 2025-08-12 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_post_doacao_disponivel_alter_doacao_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doacao',
            name='data_validade',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doacao',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='doacao',
            name='unidade',
            field=models.CharField(default='unidade(s)', max_length=30),
        ),
        migrations.AlterField(
            model_name='doacao',
            name='restaurante',
            field=models.ForeignKey(limit_choices_to={'tipo_usuario': 'restaurante'}, on_delete=django.db.models.deletion.CASCADE, related_name='doacoes', to='app.usuario'),
        ),
        migrations.AlterField(
            model_name='doacao',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('reservado', 'Reservado'), ('doado', 'Doado'), ('expirado', 'Expirado')], default='disponivel', max_length=20),
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_atual', models.PositiveIntegerField()),
                ('alerta_validade', models.BooleanField(default=False)),
                ('doacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estoque', to='app.doacao')),
            ],
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('total_doados', models.PositiveIntegerField(default=0)),
                ('total_recebidos', models.PositiveIntegerField(default=0)),
                ('total_desperdicados', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='app.usuario')),
            ],
        ),
    ]
