# Generated by Django 5.2.4 on 2025-08-12 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_doacao_data_validade_doacao_quantidade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doacao',
            name='data_validade',
        ),
        migrations.RemoveField(
            model_name='doacao',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='doacao',
            name='unidade',
        ),
        migrations.AlterField(
            model_name='doacao',
            name='restaurante',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='doacao',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Relatorio',
        ),
    ]
