# Generated by Django 5.2.4 on 2025-08-12 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_doacao_data_validade_remove_doacao_quantidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('total_doados', models.PositiveIntegerField(default=0)),
                ('total_recebidos', models.PositiveIntegerField(default=0)),
                ('total_desperdicados', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='app.usuario')),
            ],
        ),
    ]
