# Generated by Django 5.2.4 on 2025-08-13 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_relatorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='doacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.doacao'),
        ),
    ]
